default:
  image: python:3.9-bullseye

stages:
  - test
  - deploy

python:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq tox
    - apt-get install git
    - tox -e cov-init,py3,cov-report
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - coverage_html_report
    expire_in: 1 day

deploy_development:
  stage: deploy
  variables:
    # Set to use GSPs private pypi index
    TWINE_USERNAME: "${PRIVATE_PYPI_USERNAME}"
    TWINE_REPOSITORY_URL: "${PRIVATE_PYPI_URL}"
    TWINE_PASSWORD: "${PRIVATE_PYPI_PASSWORD}"
  script:
    - python -m pip install -U twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - develop

deploy_development_models:
  stage: deploy
  variables:
    # Set to use GSPs private pypi index
    TWINE_USERNAME: "${PRIVATE_PYPI_USERNAME}"
    TWINE_REPOSITORY_URL: "${PRIVATE_PYPI_URL}"
    TWINE_PASSWORD: "${PRIVATE_PYPI_PASSWORD}"
  script:
    - python -m pip install -r requirements.txt
    - ./create_models.sh
    - cd models
    - python -m pip install -U twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - develop

deploy_production:
  stage: deploy
  variables:
    # Set to use https://pypi.org/
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: "${PYPI_API_TOKEN}"
  script:
    - python -m pip install -U twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - master

deploy_production_models:
  stage: deploy
  variables:
    # Set to use https://pypi.org/
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: "${PYPI_API_TOKEN}"
  script:
    - python -m pip install -r requirements.txt
    - ./create_models.sh
    - cd models
    - python -m pip install -U twine
    - python setup.py sdist bdist_wheel
    - python -m twine upload dist/*
  only:
    - master
