default:
    image: python:3.8-bullseye

stages:
  - test

python:
  stage: test
  script:
    - apt-get update -qq && apt-get install -y -qq tox
    - apt-get install git
    - tox -e cov-init,py3,cov-report
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    paths:
      - coverage_html_report
    expire_in: 1 day
